export const SIGNIN_USER = "signin_user";
export const SIGNUP_USER = "signup_user";
export const AUTH_USER = "auth_user";

export const GET_SUPPLIER_REQUEST = "GET_SUPPLIER_REQUEST";
export const GET_SUPPLIERS_REQUEST = "GET_SUPPLIERS_REQUEST";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_FAILUAR = "GET_SUPPLIERS_FAILUAR";
export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_SUPPLIER = "CHANGE_SUPPLIER";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export const GET_CATEGORYS_REQUEST = "GET_CATEGORYS_REQUEST";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_INIT = "GET_PRODUCTS_INIT";
export const ORDER_INCREMENT = "ORDER_INCREMENT";
export const ORDER_DECREMENT = "ORDER_DECREMENT";
export const ORDER_INPUT_CHANGE = "ORDER_INPUT_CHANGE";
export const ORDER_CHANGE_INPUT = "ORDER_CHANGE_INPUT";